name: .NET

on:
  push:
    branches: ["main"] # Oder entferne das, um alle Branches zu erfassen
  pull_request:
    branches: ["main"]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # WICHTIG: Holt alle Commits

      - name: Send Webhook to Discord
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1336057220126867496/AOYd9hxIECZVKDycMQZ_mrNLfWDmQcfQwSXUqH8mAugNwKaKeC0wqL72VCUI9MDnGbt1"
        run: |
          # Fallback, falls kein "before"-SHA vorhanden ist
          BEFORE_SHA="${{ github.event.before }}"
          if [ -z "$BEFORE_SHA" ]; then
            BEFORE_SHA=$(git rev-list --max-parents=0 HEAD)
          fi

          # Geänderte Dateien ermitteln
          CHANGED_FILES=$(git diff --name-only "$BEFORE_SHA" "${{ github.sha }}")

          # Zeitstempel und Infos
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          BRANCH="${GITHUB_REF#refs/heads/}"
          USER="${{ github.actor }}"
          REPO="${{ github.repository }}"

          # Dateien formatieren oder Platzhalter setzen
          if [ -z "$CHANGED_FILES" ]; then
            FORMATTED_FILES="Keine Änderungen gefunden."
          else
            FORMATTED_FILES=$(echo "$CHANGED_FILES" | awk '{printf "- %s\n", $0}')
          fi

          # JSON Payload
          PAYLOAD=$(jq -n \
            --arg title "Push Event in Repository: $REPO" \
            --arg branch "$BRANCH" \
            --arg user "$USER" \
            --arg timestamp "$TIMESTAMP" \
            --arg changed_files "$FORMATTED_FILES" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "color": 3066993,
                  "fields": [
                    {"name": "Branch", "value": $branch, "inline": true},
                    {"name": "User", "value": $user, "inline": true},
                    {"name": "Date and Time", "value": $timestamp, "inline": true},
                    {"name": "Changed Files", "value": $changed_files, "inline": false}
                  ]
                }
              ]
            }'
          )

          # Webhook senden
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
