name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Send Webhook to Discord
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1336057220126867496/AOYd9hxIECZVKDycMQZ_mrNLfWDmQcfQwSXUqH8mAugNwKaKeC0wqL72VCUI9MDnGbt1"
        run: |
          # Ensure the latest commit data is available
          git fetch --prune --unshallow || true
          
          # Get the changed files
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
          
          # Check if more than two files changed
          FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l)
          if [ "$FILE_COUNT" -le 2 ]; then
            echo "Less than or equal to 2 files changed. Skipping webhook."
            exit 0
          fi

          # Prepare data
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          BRANCH="${GITHUB_REF#refs/heads/}"
          USER="${{ github.actor }}"
          REPO="${{ github.repository }}"

          # Send Discord webhook
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
                  "embeds": [
                    {
                      "title": "Push Event in Repository: '"$REPO"'",
                      "color": 3066993,
                      "fields": [
                        { "name": "Branch", "value": "'"$BRANCH"'", "inline": true },
                        { "name": "User", "value": "'"$USER"'", "inline": true },
                        { "name": "Date and Time", "value": "'"$TIMESTAMP"'", "inline": true },
                        { "name": "Changed Files", "value": "'"$(echo "$CHANGED_FILES" | tr '\n' ', ')"'", "inline": false }
                      ]
                    }
                  ]
                }'
